### ISSUE TITLE
CLI: optional or required arguments?

### ISSUE THREAD

**Issue by matrixise** [python-gitlab/python-gitlab#1047]
## Description of the problem, including code/CLI snippet

Some arguments are "optional" but the CLI parser says the opposite
```
> gitlab -o yaml -f id,name project search -h                                                                                   usage: gitlab project search [-h] --id ID --scope SCOPE --search SEARCH

optional arguments:
  -h, --help       show this help message and exit
  --id ID
  --scope SCOPE
  --search SEARCH
> gitlab -o yaml -f id,name project search --id 10
usage: gitlab project search [-h] --id ID --scope SCOPE --search SEARCH
gitlab project search: error: the following arguments are required: --scope, --search
```

## Expected Behavior

Optional arguments

## Actual Behavior

Required arguments

## Specifications

  - python-gitlab version: 2.1.2
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.4.2-ee

**Comment by nejch** [comment]
For anyone stumbling across this years later:

This appears to be a terminology thing with argparse, because flags (`--something`) were historically called "optionals" as opposed to positional args. It's not a python-gitlab thing per se, but upstream python (of course we could improve this by grouping arguments into some named groups if we invested any more time in argparse..).

Context: https://bugs.python.org/issue9694

**Comment by JohnVillalovos** [comment]
This seems to "fixed" now. At least with Python 3.10. I get the following:

```
$ gitlab -o yaml -f id,name project search -h
usage: gitlab project search [-h] --id ID --scope SCOPE --search SEARCH

options:
  -h, --help       show this help message and exit
  --id ID
  --scope SCOPE
  --search SEARCH
```

It no longer calls them `optional arguments` but calls them `options`.
