### ISSUE TITLE
Project.name missing

### ISSUE THREAD

**Issue by Bengt** [python-gitlab/python-gitlab#1119]
I noticed that Project.name does not exist, while GroupProject.name exists and is populated. As a workaround, I just used the name attribute of the GroupProject whose id I used to look up the project in the first place.

**Comment by Bengt** [comment]
Money Code:

    project.name = group_project.name

https://gitlab.com/designetz.time-tracker/Designetz.Time-Tracker/-/blob/master/time_tracker/gitlab_pkg/generate_commits_for_gitlab_module.py#L43

**Comment by nejch** [comment]
The name is definitely there, you're probably getting this because you're creating a lazy object in your code (https://gitlab.com/designetz.time-tracker/Designetz.Time-Tracker/-/blob/2461fa3add4a841633f8c6b6ad4b9276144c1725/time_tracker/gitlab_pkg/generate_commits_for_gitlab_module.py#L41) so the API call is never made when you're trying to access the attribute. Can you try without `lazy=True`?

See:
```
>>> gl = gitlab.Gitlab('https://gitlab.com')
>>> project = gl.projects.get('gitlab-org/gitlab')
>>> project.name
'GitLab'

```

**Comment by Bengt** [comment]
Hi, @nejch. Yes, I can confirm the attribute existing and getting populated when I use `lazy=False`. Thanks for the pointer, I must have overlooked this information when referring to the documentation. I removed my workaround and my code is now a little cleaner. Great!
