### ISSUE TITLE
import_project with namespace that exists throws that the namespace does not exists (404)

### ISSUE THREAD

**Issue by maximatt** [python-gitlab/python-gitlab#1134]
## Description of the problem, including code/CLI snippet
I have already created a group (_gtest_), which their id is _154_
Looking for it and importing the project:
```
print('*** ',gl.namespaces.list(search='gtest'))
output = gl.projects.import_project(open(f,'rb'),projectName,str(parentId),True)
```
Notes: 
- _parentId_ has 154 as value
- _f_ contais the full path of the exported project
- _projectName_ contains the name of the project
- the group was created with the same user as _gl_ was authenticated 
## Expected Behavior
      project imported

## Actual Behavior
```
***  [<Namespace id:154>]
.....
gitlab.exceptions.GitlabHttpError: 404: 404 Namespace Not Found
```
## Specifications

  - python-gitlab version: 2.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.1.2 ce

Thanks in advance!

**Comment by Shkurupii** [comment]
Hello!
I tried to reproduce your issue. What I found you pass arguments in the wrong order or you miss to declare one parameter. That's why I think you end up with an exception.
As you can see function [import_project](https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects/__init__.py#L5344) expect the next parameters: 
```
        file,
        path,
        name=None,
        namespace=None,
        overwrite=False,
        override_params=None,
        **kwargs
```
Order matters. According to the order of parameters above let's look at your code snippet and how the function treats your arguments:
```
output = gl.projects.import_project(open(f,'rb'),projectName,str(parentId),True)
```
file - open(f,'rb')
path - projectName
name - str(parentId)
namespace - True

And namespace "True" not found (404)
 
For example the correct way to import a project will be:
```
output = gl.projects.import_project(file=open('/tmp/export.tgz', 'rb'), path='my_new_project', namespace=8)
```
The name of the project to be imported is by defaults equals to the path of the project if not provided.

**Comment by nejch** [comment]
Hmm maybe the examples in the docs could provide more detail since it's a custom method and people might get confused by positional and keyword arguments here.
