### ISSUE TITLE
Option to get all the projects in (sub)group

### ISSUE THREAD

**Issue by zabbal** [python-gitlab/python-gitlab#1151]
## Description of the problem, including code/CLI snippet

Right now there seems to be no way got get all the projects belonging to a particular (sub)group.
Something like 
`python-gitlab -c ~/.config/gitlab-cli project get --group mygroup
`
## Expected Behavior
`python-gitlab -c ~/.config/gitlab-cli project get --group mygroup
`
should checkout mygroup/prj1, mygroup/prj2, ... mygroup/prjN

## Actual Behavior
The option doesn't seem to be available via cli.

## Specifications

  - python-gitlab version: 2.0.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):gitlab.com

**Comment by nejch** [comment]
You can list all projects of a group with the following:

`gitlab group-project list --all --group-id <group ID>`

This will output project ID's of all the projects. Since you mention subgroups, if you need to recurse into subgroups:

`gitlab group-project list --all --include-subgroups true --group-id <group ID>`

Does this answer your question? Not sure what you meant by "checkout", but you can use a proper git client to actually clone the projects (using URL's after collecting project details from the above command), if that's what you mean.

**Comment by zabbal** [comment]
Seems like a viable workaround, thanks.
