### ISSUE TITLE
Feature request: Use group access token

### ISSUE THREAD

**Issue by ikreb7** [python-gitlab/python-gitlab#1196]
## Description of the problem, including code/CLI snippet

    gg = gitlab.Gitlab('https://<gitlab-server>.com/', group_token='5yXtzzRGJxUSSXWB5Fc')
    gg.auth()

   repos = gg.repos.list()
   for repo in repos:
       print(repo)

  gg.create_repo("Test repo 01")

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):  13.3.6

**Comment by nejch** [comment]
Hi @ikreb7, group access tokens are not implemented yet in GitLab, see: https://gitlab.com/gitlab-org/gitlab/-/issues/214046

Once they are implemented upstream, you will immediately be able to use them in `python-gitlab` via `private_token` (rather than `group_token`!), as is already the case with project access tokens: https://docs.gitlab.com/ee/api/README.html#personalproject-access-tokens

Maybe you're thinking of group deploy tokens. Those unfortunately don't have an API scope so you will not be able to use them to create projects as suggested in your snippet above, see:

![image](https://user-images.githubusercontent.com/16777978/94442969-e0a36100-01a4-11eb-90bd-75146b480bb0.png)

I'll close this but feel free to re-open if this doesn't answer your question :)
