### ISSUE TITLE
Accepting 'empty' merge request raises `GitlabMRClosedError`

### ISSUE THREAD

**Issue by valentingregoire** [python-gitlab/python-gitlab#1198]
## Description of the problem, including code/CLI snippet
When accepting a merge request which is open, but has no changes, a `GitlabMRClosedError` is raised.
```python
merge_request.merge()
```
Some attributes (removed sensitive data) of the merge request while debugging:
```python
{
	'id': 13083,
	'iid': 55,
	'project_id': 1,
	'title': 'some title',
	'description': None,
	'state': 'opened',
	'created_at': '2020-09-29T12:58:50.487+02:00',
	'updated_at': '2020-09-29T12:58:50.487+02:00',
	'merged_by': None,
	'merged_at': None,
	'closed_by': None,
	'closed_at': None,
	'target_branch': 'master',
	'source_branch': 'development',
	'user_notes_count': 0,
	'upvotes': 0,
	'downvotes': 0,
	'source_project_id': 1,
	'target_project_id': 1,
	'labels': [],
	'work_in_progress': False,
	'milestone': None,
	'merge_when_pipeline_succeeds': False,
	'merge_status': 'cannot_be_merged',
	'merge_commit_sha': None,
	'squash_commit_sha': None,
	'discussion_locked': None,
	'should_remove_source_branch': None,
	'force_remove_source_branch': False,
	'reference': '!55',
	'time_stats': {
		'time_estimate': 0,
		'total_time_spent': 0,
		'human_time_estimate': None,
		'human_total_time_spent': None
	},
	'squash': False,
	'task_completion_status': {
		'count': 0,
		'completed_count': 0
	},
	'has_conflicts': True,
	'blocking_discussions_resolved': True,
	'subscribed': True,
	'changes_count': None,
	'latest_build_started_at': None,
	'latest_build_finished_at': None,
	'first_deployed_to_production_at': None,
	'pipeline': None,
	'head_pipeline': None,
	'merge_error': None,
	'first_contribution': False,
	'user': {
		'can_merge': True
	}
}
```

## Expected Behaviour
Another type of `GitlabMR*Error` is raised.

## Actual Behaviour
A `GitlabMRClosedError` is raised.

## Specifications

  - python-gitlab version: 2.3.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.4.1

**Comment by nejch** [comment]
It seems like, way back in 2015, `python-gitlab` had a better way of parsing error responses that was lost with introduction of the more generic `on_http_error` decorator:

https://github.com/python-gitlab/python-gitlab/blob/374a6c4544931a564221cccabb6abbda9e6bc558/gitlab/exceptions.py#L178-L212

Probably best to bring back the ability to parametrize the error based on the response code. In the case of MR merges, the API gives a few different responses:

> If merge request is unable to be accepted (ie: Draft, Closed, Pipeline Pending Completion, or Failed while requiring Success) - you’ll get a 405 and the error message ‘Method Not Allowed’
> 
> If it has some conflicts and can not be merged - you’ll get a 406 and the error message ‘Branch cannot be merged’
> 
> If the sha parameter is passed and does not match the HEAD of the source - you’ll get a 409 and the error message ‘SHA does not match HEAD of source branch’
> 
> If you don’t have permissions to accept this merge request - you’ll get a 401 

But this also means that for backwards compatibility, all `GitlabMR*Error`s would have to be subclassed from `GitlabMRClosedError` rather than vice versa, as people may be using that already (pretty sure I also have them sprinkled around my scripts), maybe until a major version bump. 😁

**Comment by max-wittig** [comment]
I guess we can close this one then.
