### ISSUE TITLE
pipeline.jobs.list() does not returning failed jobs

### ISSUE THREAD

**Issue by wallhided** [python-gitlab/python-gitlab#1219]
When I use pipeline.jobs.list() it isn't return failed jobs , if this job was success after retry.
Problem started a week ago.
I have 268 jobs in pipeline , but api returns only 266.

**Comment by nejch** [comment]
Probably an upstream API change again since nothing changed in `python-gitlab`. Do you get the same behavior if you try with other HTTP clients?

**Comment by wallhided** [comment]
tried with curl 
`jobs?scope=failed`
returned nothing.

**Comment by nejch** [comment]
Since you're saying it started a week ago and your curl example has the same issue (no failed jobs returned), I'd say this was introduced upstream with this merge request refactoring the `jobs_finder`, from October 19th.

https://gitlab.com/gitlab-org/gitlab/-/merge_requests/45558/diffs

Could you open an issue upstream https://gitlab.com/gitlab-org/gitlab/-/issues ?

**Comment by wallhided** [comment]
https://gitlab.com/gitlab-org/gitlab/-/issues/273000

**Comment by nejch** [comment]
@wallhided I think this was fixed upstream in 13.9, please reopen otherwise :)
