### ISSUE TITLE
Setting page for a paginated endpoint returns a list, ignoring the as_list=False kwarg

### ISSUE THREAD

**Issue by FreebeJan** [python-gitlab/python-gitlab#1235]
## Description of the problem, including code/CLI snippet

Setting page for a paginated endpoint returns a list even when used with `as_list=False`

This is an issue when you want to consume the total_pages and totals information.

The culprit is this snippet in the [__init__.py file](https://github.com/python-gitlab/python-gitlab/blob/784cba659a9d15076711f5576549b4288df322cc/gitlab/__init__.py) starting on line 644

```python
        if page or as_list is True:
            # pagination requested, we return a list
            return list(GitlabList(self, url, query_data, get_next=False, **kwargs))
```

## Expected Behavior

Setting `as_list=False` should not return a list

## Actual Behavior

Setting `as_list=False` returns a list when `page`is set

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v4): irrelevant
  - Gitlab server version (or gitlab.com): irrelevant

**Comment by ramedlawH** [comment]
I ran into the same problem. I think the reason why `total_pages` is not working anymore is because Gitlab removed the `X-Total` and `X-Total-Pages` from the headers on which the python-gitlab module is depending on. 
https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/client.py#L844

Check on this Gitlab Issue: https://gitlab.com/gitlab-org/gitlab/-/issues/264375

In my special case I have to get the last page of the commits. I changed the code this way:

```
# Before:
last_page = project.commits.list(as_list=False, per_page=1).total_pages
# After:
last_page = len(project.commits.list(all=True, as_list=True))
```

**Comment by max-wittig** [comment]
@ramedlawH Exactly. That's not really anything we can fix sadly and they don't want that fixed. See also: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34273
