### ISSUE TITLE
Gitlab CLI typo in current-user-gpg-key

### ISSUE THREAD

**Issue by tback** [python-gitlab/python-gitlab#1289]
## Description of the problem, including code/CLI snippet
The command to list gpg keys of the current user contains a typo

```
gitlab current-user-gpg-keys
```

## Expected Behavior
```
[List of users gpg keys]
```

## Actual Behavior
```
gitlab current-user-gpg-keys
gitlab: error: argument what: invalid choice: 'current-user-gpg-keys'...

gitlab current-user-gp-gkeys
Traceback: ...

KeyError: CurrentUserGpGkey
```

## Specifications

  - python-gitlab version: 2.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.3.9

**Comment by nejch** [comment]
Hi @tback, currently the CLI commands are dynamically converted from CamelCase classes (to create commands for the CLI) and vice versa (to parse them from the CLI). The library incorrectly assumes those are separate words because of the uppercase in UserGPGKey.

As stated in the docs these are all auto-generated, so some may not work as expected currently. This might need some hardcoded exception list in a few cases :thinking:
