### ISSUE TITLE
Unexpected behaviour for group.projects.list()

### ISSUE THREAD

**Issue by matthias-reiff** [python-gitlab/python-gitlab#1293]
Hi, I'm not sure if this is expected behaviour:

I have a group that itself contains no projects as child elements.
But there are projects, that are shared to this group (by using `project.share(group.id, gitlab.DEVELOPER_ACCESS)` before).

When I'm doing this:
`projects = group.projects.list()`

I would expect an empty list. 
But I get a list of the projects that have been shared to this group.

Is there a way to filter out projects that have been shared, like the filter for archived?
Is there a way to get only projects that have the group as _real_ parent?

------
In page: gl_objects/groups.rst

**Comment by nejch** [comment]
Hi @matthias-reiff,

Yes, this is expected behavior with the current GitLab API. It's possible that the response has changed at some point, I seem to remember something changed with groups sometime in 13.x.

According to upstream docs in https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects, see the `with_shared` parameter:

> `with_shared | boolean | no | Include projects shared to this group. Default is true`

Pass it as false to the API and it should work as expected. Please re-open if you still have issues! :)

**Comment by matthias-reiff** [comment]
Hi @nejch, thank you very much!
