### ISSUE TITLE
Discussions API is missing (again?)

### ISSUE THREAD

**Issue by Max55767** [python-gitlab/python-gitlab#1315]
## Description of the problem, including code/CLI snippet
Related to the old problem https://github.com/python-gitlab/python-gitlab/issues/501 the discussions API seems to be missing in v2.6.0.

```python
conn = gitlab.Gitlab('https://gitlab.com', private_token=access_token)
issue = conn.issues.list()[0]
issue.discussions
```

This yields a `KeyError` because `discussions` is not part of `issue`.

## Expected Behavior
With `.discussions` you can access all discussions in MRs and issues as described in the docs: https://python-gitlab.readthedocs.io/en/stable/gl_objects/discussions.html (The docs probably also need an update...)

## Actual Behavior
`KeyError` discussions is not found

## Specifications

  - python-gitlab version: v2.6.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
The way you are trying to access discussions is not how it's described in the docs (emphasis mine):

>  Discussions are available for **project issues**, merge requests, snippets and commits.

First - you need to create a proper ProjectIssue object on which you can call methods, not just one from the list from the API response (see FAQ https://python-gitlab.readthedocs.io/en/stable/faq.html).

Then, remember `discussions` is not just an attribute but a manager in `ProjectIssue` to call methods on. A full example would be:

```python
conn = gitlab.Gitlab('https://gitlab.com', private_token=access_token)
issues = conn.issues.list()

# Get to a proper ProjectIssue object
project = conn.projects.get(issues[0].project_id, lazy=True)
issue = project.issues.get(issues[0].id, lazy=True)

# As shown in https://python-gitlab.readthedocs.io/en/stable/gl_objects/discussions.html
discussions = issue.discussions.list()
```
But I agree you have to piece it together from different parts of the docs. I'll leave this open for another week in case you'd like to contribute the docs for this to make it clearer?

Note this is the case for almost all objects. You need to create a resource and call its methods, not just use the GitLab's API response from a list. Because that initial response from the server does not have the details you need, `python-gitlab` needs to make more calls to get that. Here's some more discussion on this topic if it helps: https://github.com/python-gitlab/python-gitlab/issues/1138#issuecomment-670723726

**Comment by nejch** [comment]
Closing this as there was no more feedback. See also https://python-gitlab.readthedocs.io/en/latest/faq.html
