### ISSUE TITLE
Find merge request by commit sha

### ISSUE THREAD

**Issue by mpushki** [python-gitlab/python-gitlab#1374]
I can use search in `pygithub`:
`g.search_issues(f"repo:<name> is:pr <commit_sha>")`
There is the same logic for `python-gitlab`?

**Comment by nejch** [comment]
Hi @mpushki, I think this unfortunately not supported by the Search API in GitLab Core. 
It might be covered by Elasticsearch, but since it's a Premium feature there's no way we can test it.

https://docs.gitlab.com/ee/api/search.html#scope-merge_requests-2

If you have GitLab Premium or Ultimate, you can give it a try - something like this.

Global search:
```python
import gitlab

gl = gitlab.Gitlab(GITLAB_URL, private_token=GITLAB_TOKEN)

gl.search(scope="merge_requests", search="b4074ef1")

# Or commit scope
gl.search(scope="commits", search="b4074ef1")
```

Project-scoped search:
```python

import gitlab

gl = gitlab.Gitlab(GITLAB_URL, private_token=GITLAB_TOKEN)
project = gl.projects.get(GITLAB_PROJECT)

project.search(scope="merge_requests", search="b4074ef1")

# Or commit scope
project.search(scope="commits", search="b4074ef1")
``` 

Since all the Search API functionality is already covered by python-gitlab I'll close this but you can open an issue upstream at https://gitlab.com/gitlab-org/gitlab and link it here. Also feel free to re-open this if it's unclear.
