### ISSUE TITLE
ImportError: cannot import name 'GitlabGetError' from 'gitlab.v4.objects'  on V. 2.7.0/2.7.1

### ISSUE THREAD

**Issue by omersi** [python-gitlab/python-gitlab#1423]
## Description of the problem, including code/CLI snippet
When running job it triggers the following exception

```python
Traceback (most recent call last):
  File "ops_tools/duplicate_app.py", line 16, in <module>
    from utils.gitlab_utils import GitlabHandler
  File ".../ops_tools/utils/gitlab_utils.py", line 14, in <module>
    from gitlab.v4.objects import GitlabGetError, Project, ProjectBranch, \
ImportError: cannot import name 'GitlabGetError' from 'gitlab.v4.objects' 
```

Tested with `2.6.0` and the module works as expected

## Expected Behavior

Fix the issue. 

## Specifications

  - python-gitlab version: 2.7.1
  - API version you are using (v3/v4): V4
  - Gitlab server version (or gitlab.com):  13.6.3-ee

**Comment by nejch** [comment]
Hi @omersi, please just use `from gitlab.exceptions import GitlabGetError` instead. It was more of an internal detail that the exceptions were imported there, but you should really use them as documented here:

https://python-gitlab.readthedocs.io/en/stable/api/gitlab.html#module-gitlab.exceptions

Otherwise if you saw this documented somewhere and it should be fixed in our docs, please link it here and reopen this, thanks! :)
