### ISSUE TITLE
Missing public_builds attribute when retrieving project

### ISSUE THREAD

**Issue by giovanni-riva** [python-gitlab/python-gitlab#1428]
## Description of the problem, including code/CLI snippet

The `Project`'s atribute `public_builds` is wrongly called `public_jobs`.
This prevents enabling/disabling `public pipelines` in a project.

(The setting is the following: `Gitlab project > Settings > CI/CD > General pipelines > check "Public pipelines"`)

## Expected Behavior

```
prj = gl.projects.get(project_id)
print(prj.public_builds) # is set to True

prj.save(public_builds = False)

# alternatively
# prj.public_builds = False
# prj.save()

```

## Actual Behavior

```
prj = gl.projects.get(project_id)
print(prj.public_jobs) # is set to True
print(prj.public_builds) # attribute missing

prj.public_jobs = False
prj.save() # error: missing one positional argument

prj.save(public_builds=False) # no changes
```

## Work around

```
prj = gl.projects.get(project_id)
prj.public_builds = False # we need to define the variable
prj.save() 
```

## Specifications

  - python-gitlab version: 2.7.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.12.0-pre 61130ebf9ea

**Comment by nejch** [comment]
Hi @giovanni-riva,

actually, `public_builds` is a deprecated attribute in GitLab's API, so you should use `public_jobs` instead. This is why you get an AttributeError, because the gitlab server does not return it anymore. It is only supported for the `update` method in GitLab for backwards compatibility.

I've opened #1439 to add `public_jobs` so you should be able to use that after it's merged.

**Comment by nejch** [comment]
Upstream issue: https://gitlab.com/gitlab-org/gitlab/-/issues/329725
