### ISSUE TITLE
How to get full diff output via API?

### ISSUE THREAD

**Issue by bobbywatson3** [python-gitlab/python-gitlab#1534]
## How is it possible to get the full diff output?

I'd like the output in the same format as https://patch-diff.githubusercontent.com/raw/python-gitlab/python-gitlab/pull/1.diff

Sorry, I know this is more of a question than a bug, but I can't find a way to do this in the documentation.

## Specifications

  - python-gitlab version: 2.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by bobbywatson3** [comment]
I'm specifically asking because I'd like to be able to load it into unidiff: https://github.com/matiasb/python-unidiff

**Comment by JohnVillalovos** [comment]
Did you look at: https://python-gitlab.readthedocs.io/en/stable/gl_objects/commits.html

**Comment by nejch** [comment]
Hi @bobbywatson3, there are several API endpoints that return diffs. Do you need it for:
- diff of a commit (from https://docs.gitlab.com/ee/api/commits.html#get-the-diff-of-a-commit)
- diff from a specific MR version (from https://docs.gitlab.com/ee/api/merge_requests.html#get-a-single-mr-diff-version)
- diff of an entire merge request ("MR changes") (https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-changes)

Here are a few pointers:
- Commit diff: https://python-gitlab.readthedocs.io/en/stable/gl_objects/commits.html?highlight=diff#examples
- MR single diff: https://python-gitlab.readthedocs.io/en/stable/gl_objects/mrs.html?highlight=diff#id2
- MR changes: https://python-gitlab.readthedocs.io/en/stable/gl_objects/mrs.html?highlight=changes#id2

With some endpoints you might need to construct your own to get a unified diff because of how the API returns it - a list of items for each file where the `diff` attribute contains the diff itself so let us know.

**Comment by bobbywatson3** [comment]
Thanks so much for the quick responses!

I'm trying to construct the diff for an entire MR in the same format that Gitlab outputs by just adding `.diff` to the PR URL. Example: https://gitlab.com/gitlab-org/gitaly/-/merge_requests/1.diff

I was hoping there was an easy way to do this since the site itself makes it easy, but not the API I guess.

Is there an easy way in `python-gitlab` to call that URL without having to put together auth for a third party web library like `requests`?

**Comment by nejch** [comment]
Looks like we're hitting an upstream issue here where people suggest workarounds to hack together the diff headers from the json fields:

https://gitlab.com/gitlab-org/gitlab/-/issues/270960
https://gitlab.com/gitlab-org/gitlab/-/issues/24913

> Is there an easy way in `python-gitlab` to call that URL without having to put together auth for a third party web library like `requests`? I tried `http_get`, but it didn't work for a non-api URL.

You might actually have some luck if you use the full URL in `http_get` (https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/client.py#L448-L449) but this was really meant for `/api/` endpoints so I'm not sure if the type of authentication headers will be accepted by the server, you can give it a try.

**Comment by bobbywatson3** [comment]
I tried pasting in the full url, but I got a 503 back. The auth for their site appears to be different than the auth for the API.

Those links you pasted were helpful. Looks like gitlab is mangling the `git diff` output for some reason. I'll see if I can fixup the output. Thank you!

**Comment by nejch** [comment]
All the info should be there so this should be possible. But it's not great UX for sure :)
