### ISSUE TITLE
are tests required to be packaged into the wheel ?

### ISSUE THREAD

**Issue by dzen** [python-gitlab/python-gitlab#1586]
## Description of the problem, including code/CLI snippet
Simple question here : our CI/CD is crashing because the wheel does package the tests, which clashes with our current code.
I think polluting the python path with such common package name is not recommended.

What is your thoughts about it ?

## Expected Behavior
A local application with tests does find the local tests, not the python-gitlab one's

## Actual Behavior
The current version ships a "tests" package which clashes with local tests module

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): N/A

**Comment by nejch** [comment]
I see this issue was introduced with https://github.com/python-gitlab/python-gitlab/pull/1562/files which turned it into a package.

Originally the tests were bundled as some downstream package maintainers run tests against the installed dist and not the git repo, see https://github.com/freebsd/freebsd-ports/blob/main/devel/py-python-gitlab/Makefile#L55 and https://github.com/python-gitlab/python-gitlab/issues/907 for an example.

But with our move to the pytest structure this doesn't make sense anymore, true. Off the top of my head I don't know a clean way other than putting at least unit tests back in the gitlab namespace if we want to bundle them for package maintainers, but we should take a look at other options maybe.

**Comment by dzen** [comment]
Great Thank you for your quick response!
