### ISSUE TITLE
gl.groups.list() returns groups that do not meet the criterion

### ISSUE THREAD

**Issue by bbagadd** [python-gitlab/python-gitlab#1600]
## Description of the problem, including code/CLI snippet
gl.groups.list(search='g471') returns more, than I need, included some subgroups.

## Expected Behavior

[ 'results / results / g471']
## Actual Behavior

['results / results / g471 / 1000', 'results / results / g471']
## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4 
  - Gitlab server version : gitlab.com

**Comment by nejch** [comment]
Hi @bbagadd, I believe this is expected behavior because you are using the search filter and not the `get()` method.

So what is returned depends on what the gitlab server makes of your search term - it seems like subgroups that match the name are included in GitLab's results, not something `python-gitlab` can control. You would get the same if you search like that in the GUI.

If you need a single group without risking other results appearing due to the search filter, use the path directly instead: `gl.groups.get("results/g471")`

Feel free to re-open if anything is unclear!
