### ISSUE TITLE
repository_archive is not available on UserProject and GroupProject

### ISSUE THREAD

**Issue by dAnjou** [python-gitlab/python-gitlab#1760]
Hi,

like the title says `repository_archive`, or any of the methods in `RepositoryMixin`, don't seem to be available on `UserProject` and `GroupProject`.

All of them only seem to require the project ID. Is there a reason for them not to be available?

I'll have a quick look whether I can make it work.

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment]
You're hitting the same issue as the first question in the FAQ regarding group issues:
https://python-gitlab.readthedocs.io/en/stable/faq.html

These endpoints do not exist in the GitLab API so python-gitlab does not provide them. You need to create a `Project` object (you can do so lazily to avoid extra API calls) using the ID you've retrieved via user or group project in order to use those endpoints.

We've thought about making this a little easier by adding something like a `make_editable()` method or so, which would create the editable object for you.

I'll close this for now but please re-open if you think it's unclear or not documented properly. :)
