### ISSUE TITLE
Allow upload generic package from bytes

### ISSUE THREAD

**Issue by dAnjou** [python-gitlab/python-gitlab#1815]
Hi,

```python
gl = Gitlab()
project = gl.projects.get(project_id)
```
Project file upload allows both, path or bytes:
```python
file = project.upload(
    filename="my_file.txt",
    filepath="/path/to/my_file.txt",
    # or
    filedata=b"content",
)
```
But project generic package upload only allows path:
```python
package = project.generic_packages.upload(
    package_name="my_package",
    package_version="0.1",
    file_name="my_file.txt",
    path="/path/to/my_file.txt",
    # no bytes allowed :(
)
```
---
I'm happy to work on this, but I'd like to discuss with you first.

I might be too pedantic here but I like consistent argument naming. Both methods already have inconsistent argument names, `filename` and `file_name`, but I guess there's not too much you can do about it without a breaking change, unless you'd be okay with having a weird function signature that allows both for some time while deprecating the old names.

Then there are `filepath` and `path`, so considering there is `filedata` in project file upload, maybe `data` could be used in project generic package upload?

Ideally though, a much cleaner approach would be to accept a file-like object exclusively, considering how easy it is to create one: `pathlib.Path("my_file.txt").open("rb")` or `io.BytesIO(b"content")`. This would result in simpler code, less stuff to test and maintain, and arguably more flexibility for users.

What do you think?

**Comment by nejch** [comment]
Hi @dAnjou thanks a lot for starting this discussion! Since I added that initially, I can try to explain the context for the inconsistencies as I also like consistent arguments, and with some features added years ago we do have to make breaking changes to get there.

I think the idea was actually to _be_ consistent - at least with the upstream API, and I think I was deciding about the naming convention for a while when adding it. You can probably see that as I initially started off basing it on the file upload method and I still have a typo in there (a sneaky `filepath` in the docstring). I even wanted an `UploadMixin` initially but for some reason thought it would be too messy in the end.

So the reason for `file_name` was to follow the [API description](https://docs.gitlab.com/ee/user/packages/generic_packages/). It also seemed more consistent with the `package_*` params there. Why I then went for `path` I can't remember exactly :( I believe I wanted to distinguish it from `new_file_path` which is supposedly returned by the API, but means something else (the path on the server).

So at least for `file_name` I'd keep it as is, to be consistent with upstream (that should have been done for the file upload if you look at [files API](https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository)). We could potentially bring that together in a breaking change eventually. For `path` we have some freedom as it's our internal thing but that `new_file_path` makes it a bit awkward to me.

In general, it will be hard to stay consistent across the board because of upstream, see for example `filepath` in the [releases API](https://docs.gitlab.com/ee/api/releases/#create-a-release).

---

As for bytes, I'm sorry I totally missed that use case at the time! :facepalm: Although generic packages use the `api/v4` endpoints they are actually documented elsewhere, with the rest of the packages, so I assumed the primary use case was the CLI with e.g. `gitlab` acting as a `twine` equivalent to publish from CI and similar. So I think I wanted a clean CLI interface that didn't need `--path @/path/to/file.txt`, although looking at it now it doesn't seem that bad :P

So for now, I'd keep letting people pass in a string as this means we don't need to write a custom CLI method for it if that's ok with you. But let me know if you disagree or have other ideas, WDYT?

But adding this would be really great. I think `data` makes sense there, as we have `server_data` for the returned data so it should still be clear. We can work out the kinks in the PR :)

**Comment by nejch** [comment]
I also like the idea of using file-like objects. Just would like to have that fallback for strings as mentioned above if that makes sense, or if the CLI override is quite clean then we can do that as well.

**Comment by dAnjou** [comment]
Thanks for the super fast response and the insights!

All in all I'm not too emotional about the naming and I'd follow your pragmatic preferences, backwards-compatibility is usually more important to me.

---

Regarding file-like object vs path or bytes, I'd very much like to give it a backwards-compatible try :P So, I guess, rather file-like object in addition to path and bytes, and then deprecating these two.

Generally, `data` sounds like the best name to me ([curl uses that as well](https://curl.se/docs/manpage.html#-d)). So, I'd suggest the following method signatures:

```python
class Project(...):
    def upload(
        self,
        filename: str,
        filedata: Optional[Union[bytes, BinaryIO]] = None,  # <- SEMI-NEW, then with type distiction in code
        filepath: Optional[str] = None,
        **kwargs: Any,
    ) -> Dict[str, Any]
```
```python
class GenericPackageManager(...):
    def upload(
        self,
        package_name: str,
        package_version: str,
        file_name: str,
        path: Union[str, Path],
        data: Optional[Union[bytes, BinaryIO]] = None,  # <- NEW
        **kwargs: Any,
    ) -> GenericPackage
```

Looking at the code, it seems quite difficult to expose a non-naive or even non-string argument to the CLI. But that can be a second step later, I guess?

---

While trying the generic package upload, I noticed another thing. [The docs say](https://docs.gitlab.com/ee/user/packages/generic_packages/):

> Example response without attribute `select`:
>
>     {
>       "message":"201 Created"
>     }
>
> Example response with attribute `select = package_file`:
>
>     {
>       ...big JSON object without(!) "message" key...
>     }

Currently, only the first case without `select` works. Providing `select` results in a crash because the return object construction looks like this:

```python
return self._obj_cls(
    self,
    attrs={
        "package_name": package_name,
        "package_version": package_version,
        "file_name": file_name,
        "path": path,
        "message": server_data["message"],
    },
)
```
Here I'd suggest keeping the `"message"` in the first case, and for the other case I'd use `"package_file"` as key instead.

**Comment by nejch** [comment]
@dAnjou ah that's interesting. the `select` param wasn't available when this was added, seems like they added it a few months ago https://gitlab.com/gitlab-org/gitlab/-/merge_requests/72201. This lack of any info returned is exactly why I was constructing the attributes manually in hopes of making the created object at least a bit useful :facepalm: 

If the response is complete with that param, then perhaps the return could be closer to the vanilla CreateMixin, as we have all the data?
https://github.com/python-gitlab/python-gitlab/blob/main/gitlab/mixins.py#L321-L325

I'll look at the rest later tonight but yes, the CLI has not seen much work in a while and maybe I'm a bit hesitant to invest time in it as it seems like switching to a different library for large refactors makes more sense :sweat_smile:

**Comment by iRemjeyX** [comment]
Hi, 

So is there a way to temporarily override the return statement to return the ```package_file``` key instead?

Currently I am doing it like this:

```python
project: gitlab.v4.objects.Project
package_resp = project.generic_packages.upload(
        package_name=package_name,
        package_version=version,
        file_name=file_name,
        path=file_path,
        query_data={"select": "package_file"}
    )
```

But can't really think of a nice way to let it return the ```package_file``` key without catching ```KeyError: 'message'```.
