### ISSUE TITLE
Humble proposal: replace alpine base image by python:slim

### ISSUE THREAD

**Issue by rassie** [python-gitlab/python-gitlab#1852]
## Description of the problem, including code/CLI snippet

`python-gitlab` Docker image currently uses `alpine` as its base. There are good arguments to not use Alpine, but a slim Python image instead.

## Expected Behavior

Current example: I expect DNS to work properly in the image, since I want to contact internal and external Gitlabs with `python-gitlab`.

## Actual Behavior

Currently, there is an [issue]( https://github.com/alpinelinux/docker-alpine/issues/155) preventing DNS resolution for names which don't have an AAAA DNS entry (IPv6 seems preferred). This kind of issues occurs on a regular basis with Alpine, since it's using `musl` as it's `libc`, which leads to all kind of incompatibilities with software expecting a `glibc`-like behaviour. 

Also, at least FastAPI is explicitely warning against Alpine-based images for Python projects: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#-alpine-python-warning. The particular FastAPI problem is probably less important for `python-gitlab`, but if choosing Alpine has been driven only by image size, it might provide additional leverage for a move to `python:slim`.

On the whole, this is not a definitive recommendation, but rather a pledge to consider the alternatives.

**Comment by nejch** [comment]
Thanks for the report! The `musl`/`glibc` saga alone might make it worth adding that, especially for running on various host distros in CI. But since we're deploying to GitLab's registry I see no issue of just adding another image instead of replacing it. Just have to decide on how to alias the default one, maybe `-alpine` and `-slim` with `-alpine` aliasing the default one as otherwise it'd be weird if the default was slimmer than `slim` :)

In our case, it seems our image is 24.70 MB and base slim is 41MB (if GitLab and DockerHub show compressed size consistently), and we only bundle requests and pyyaml, so FastAPI's concerns might not yet be an issue for our existing image atm. But that makes sense.

We are also currently building with kaniko which does no compression IIRC, so that could also improve in the future.

**Comment by rassie** [comment]
@nejch Thanks! Will test next week, when I get the chance!

**Comment by sanmai-NL** [comment]
You mention an incompatibility, but in my experience the defect is outside musl libc, Alpine Linux, etc. but in other tools. [Like with this defect](https://gitlab.alpinelinux.org/alpine/aports/-/issues/11879#note_111445).
