### ISSUE TITLE
gitlab.exceptions.GitlabHttpError: 405: 405 Method Not Allowed

### ISSUE THREAD

**Issue by huangyp5** [python-gitlab/python-gitlab#1939]
## Description of the problem, including code/CLI snippet
Merge a mr With a pipline task, so we added a parameter, hoping that the pipline will merge automatically when the pipline is finished, but the prompt 405 is used for merge

## Expected Behavior
merge success

## Actual Behavior
merge fail

## Specifications

  - python-gitlab version:3.2.0
  - API version you are using (v3/v4):v4
  - Gitlab server version (or gitlab.com):
<img width="1144" alt="error" src="https://user-images.githubusercontent.com/62130546/159738266-3d3800d9-71e0-4b38-ad35-43859360a7fd.png">
<img width="867" alt="error1" src="https://user-images.githubusercontent.com/62130546/159738624-1f4c02d9-4d48-49b3-8a30-f28db046f0f1.png">

**Comment by nejch** [comment]
@huangyp5 you're trying to use `Merge when pipeline succeeds` immediately after creating the MR. Creating an MR and starting a pipeline is an async process so you need to add some `wait()` or get the state of the MR before accepting it, to see that the pipeline has actually been created. Let us know if you have any more questions otherwise we'll close this :)

**Comment by nejch** [comment]
Here's an example of waiting for an MR status (merge status in this case, but you'll be looking at the pipeline status probably):

https://github.com/python-gitlab/python-gitlab/blob/5a1678f43184bd459132102cc13cf8426fe0449d/tests/functional/conftest.py#L281-L285

I'll close this for now, if you can't get it to work please re-open :)
