### ISSUE TITLE
Create Issue with file attachment

### ISSUE THREAD

**Issue by Lennart4711** [python-gitlab/python-gitlab#1969]
## Description
I want to attach a file when creating an issue. Is this possible directly in this call something like this?
```python
issue = project.issues.create({'title': 'I have a bug',
                               'description': 'Something useful here.'
                               'attachment': 'somefile.txt.'})
```

Or do I have to upload the file and then link to it like this
```python
project.upload("filename.txt", filepath="/some/path/somefile.txt")
issue = project.issues.create({'title': 'I have a bug',
                               'description': '[somefile.txt](/some/path/somefile.txt')})
```

**Comment by nejch** [comment]
As you can see in the upstream API docs, adding an attachment is not supported directly:
https://docs.gitlab.com/ee/api/issues.html#new-issue

So your second option is correct. This is actually what the UI does as well I think - when you click upload it simply adds an upload link to the description prior to posting the issue. Feel free to re-open this if anything's unclear :) and also if you think this should be documented here rather than upstream, feel free to open a documentation PR! :)
