### ISSUE TITLE
Cannot move closed issue

### ISSUE THREAD

**Issue by Lennart4711** [python-gitlab/python-gitlab#2142]
When trying to move an issue with `issue.move(other_project_id)` I sometimes get:
```
Traceback (most recent call last):
  File "C:\Users\Name\Desktop\tickettest\venv\lib\site-packages\gitlab\exceptions.py", line 330, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\Name\Desktop\tickettest\venv\lib\site-packages\gitlab\v4\objects\issues.py", line 138, in move
    server_data = self.manager.gitlab.http_post(path, post_data=data, **kwargs)
  File "C:\Users\Name\Desktop\tickettest\venv\lib\site-packages\gitlab\client.py", line 964, in http_post
    result = self.http_request(
  File "C:\Users\Name\Desktop\tickettest\venv\lib\site-packages\gitlab\client.py", line 756, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 400: Cannot move issue due to insufficient permissions!
```
After a while I figured out, that moving an issue from one project to another can only be done if the issue is opened. Maybe there should be some error message when trying to move a closed issue. It was very confusing to get a permission error while beeing the owner of both projects.

**Comment by nejch** [comment]
Hi @Lennart4711 - the confusion comes from the GitLab API's response. python-gitlab cannot know the exact reason unless the server responds with a more informative error message.

It would also not be reliable to check the local object's state to try and infer that, as it could change on the server side in the meantime.

I think your best bet is to open an upstream issue at https://gitlab.com/gitlab-org/gitlab/ and ask for a more specific server response. Looking at upstream docs at https://docs.gitlab.com/ee/api/issues.html#move-an-issue, your situation is not described at all, so I think at least some documentation needs to be updated upstream, or a better error message provided there.

Because I think there's not much we can do here reliably, I'll close this, but feel free to reopen if you disagree. If you open an upstream issue, please also link it here for future readers! :)
