### ISSUE TITLE
gl.project.get in loop

### ISSUE THREAD

**Issue by Lennart4711** [python-gitlab/python-gitlab#2144]
I want to fetch new issues in a loop like so:
```python
project = gl.projects.get(project_id)
while running:
    issues = project.issues.list(labels=CONFIG.MOVE_LABELS, state="opened")
```
My question is, should you only create a project instance once and pass it around or can i create them if needed?

**Comment by nejch** [comment]
@Lennart4711 in your case, creating the object is only done to construct the URL with the ID, so this is perfectly fine, you could even create a lazy object to prevent an unneeded call (unless you first need to check if you have access to that project before looping).

```python
project = gl.projects.get(project_id, lazy=True)
while running:
    issues = project.issues.list(labels=CONFIG.MOVE_LABELS, state="opened")
```
Btw, also check our docs on using `all=True` or `iterator=True` with `list()` in case that helps.

I guess we can close this but let us know otherwise ;)
