### ISSUE TITLE
retrieving commit stats from a ProjectMergeRequest

### ISSUE THREAD

**Issue by roth-mh** [python-gitlab/python-gitlab#2229]
## Description of the problem, including code/CLI snippet
**feature request**
There isn't a way to get the statistics associated with the commits of a given ProjectMergeRequest object
```
# project is of type Project
mrs = project.mergerequests.list(all=True)
for mr in mrs:
    comms = mr.commits(all=True)
    for commit in comms:
        # need to make a second call to get commit details through the Project object
        comm_details = project.commits.get(commit.short_id)
        comm_details.stats # and so on
```

## Expected Behavior
```
mrs = project.mergerequests.list(all=True, with_stats=True)
for mr in mrs:
    comms = mr.commits(all=True)
    for commit in comms:
        commit.stats # is populated
```

## Actual Behavior
```
mrs = project.mergerequests.list(all=True, with_stats=True)
for mr in mrs:
    comms = mr.commits(all=True)
    for commit in comms:
        # commit.stats is None
        comm_details = project.commits.get(commit.short_id)
        comm_details.stats # is populated
```

## Specifications

  - python-gitlab version: 3.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
@roth-mh this is expected behavior unfortunately, it's just the nature of REST APIs. Your second example is correct.

The MR commits API calls `GET /projects/:id/merge_requests/:merge_request_iid/commits`, which does not expose `stats`. You need to call `GET /projects/:id/repository/commits` to get the full details. See
https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-commits vs.
https://docs.gitlab.com/ee/api/commits.html#list-repository-commits

See also https://python-gitlab.readthedocs.io/en/stable/faq.html in case some of the answers covering similar topics help here.

You'd need to use the GraphQL rather than the REST APIs for this kind of flexibility without multiple API calls. That is also planned for the client at some point. I'll close this for now but please re-open if you disagree :)

**Comment by roth-mh** [comment]
@nejch Got it, thanks. I thought the API call for MR commits might make an API call to the commits endpoint behind the scenes in which case all that would need to be done is pass a filter in, but I see why that is not the case.

Thanks!
