### ISSUE TITLE
Difficulties to print trace properly

### ISSUE THREAD

**Issue by d3ployment** [python-gitlab/python-gitlab#2401]
Hello everybody,

I'm having trouble displaying the logs properly in the terminal. The aim is to allow non-gitlab users to launch pipelines from their machines (could be Shell or Powershell, so we write it in Python and wrap it).

I would like this to be as close as possible to what can be found on Gitlab interface.
Ex : 
- User launch script (it triggers a 3 jobs pipeline)
- It shows logs of first job, then logs of second job, then third job (no concurent jobs)
- At the end it displays pipeline status and exit

Here is what I have for the moment, but I'm sure there is a better way to do it

```
import gitlab
import time
import os

gl = gitlab.Gitlab(url='HIDDEN')
trigger_token = HIDDEN

variables={HIDDEN}

project_id = HIDDEN
project = gl.projects.get(project_id)

pipeline = project.trigger_pipeline('main', trigger_token, variables=variables)
jobs = pipeline.jobs.list()

job_list = []

for x in jobs:
  job_list.append(x.id)

job_list.sort()

while pipeline.finished_at is None:
  pipeline.refresh()
  for i in job_list:
    job = project.jobs.get(i)
    while job.finished_at is None:
      os.system('cls' if os.name == 'nt' else 'clear')
      print("Job :", job.id)
      print("")
      print(job.trace())
      time.sleep(15)
```

Thanks in advance for your help

**Comment by nejch** [comment]
Hi @d3ployment, could you specify exactly what issue with the API you're hitting here?

Without trying it myself, I'd say you can use `flush` with print (https://docs.python.org/3/library/functions.html#print) instead of manual clearing, and you will have to handle converting ANSI codes in the raw output into colors/formatting as is done by GitLab. Keep in mind that if things get flushed in the job logs, this is not reflected in the raw output (you will see new lines, I'm not sure you can get around this).

But these functionalities are all outside the scope of the library, as we really only wrap the API. Unless you have issues with actually fetching the raw output, I'd say we can close this issue but please feel free to share the snippet here if you get it to work as desired, for future readers ;)

**Comment by nejch** [comment]
@d3ployment I hope the answer above is sufficient, given that your issue seems to be more about how to display the data the API provides rather than API functionality of the client itself (remember the client simply returns what the server responds with).

Otherwise just reopen this or start a discussion if you need more advice :)
