### ISSUE TITLE
ProjectJob class overwrite gitlab API attribute artifacts

### ISSUE THREAD

**Issue by sunavlis** [python-gitlab/python-gitlab#2402]
## Description of the problem, including code/CLI snippet
Python class **ProjectJob** overwrites the gitlab API attribute _artifacts_ with a method.

```
gl = gitlab.Gitlab('<URL>', private_token=<token>)
project = gl.projects.get(<project_id>)

jobs = project.jobs.list(all=True)
for job in jobs:
    for artifact in job.artifacts:
        print(f"Artifact Size: {artifact['size']}")
```

## Expected Behavior
It is expected that each job of the jobs list contains a list of artifacts according to: https://docs.gitlab.com/ee/api/jobs.html

e.g.:
```
"artifacts": [
    {"file_type": "archive", "size": 1000, "filename": "artifacts.zip", "file_format": "zip"},
    {"file_type": "metadata", "size": 186, "filename": "metadata.gz", "file_format": "gzip"},
    {"file_type": "trace", "size": 1500, "filename": "job.log", "file_format": "raw"},
    {"file_type": "junit", "size": 750, "filename": "junit.xml.gz", "file_format": "gzip"}
]
```

## Actual Behavior
The _job.artifacts_ returns the artifact binaries. Or in above code sniped it contains the "method" object and results in the following exception:
```
Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: <module>)
'method' object is not iterable
```

## Possible Fix
The simplest fix would be to rename the **ProjectJob**  method _artifacts_ to _get_artifacts_. (https://github.com/python-gitlab/python-gitlab/blob/main/gitlab/v4/objects/jobs.py#L117)

In this case, _job.artifacts_ from the code snipped above contains the artifact list according to the gitlab API documentation.

## Specifications

  - python-gitlab version: 3.12.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 15.5.1

**Comment by nejch** [comment]
Hi @sunavlis! yes, sometimes our managers and methods might shadow the attributes returned by the server.

This is why we provide the `attributes` container so you can still access them like so:

```python
for job in jobs:
    for artifact in job.attributes["artifacts"]:
        print(f"Artifact Size: {artifact['size']}")
```

I'm not sure about renaming methods/managers, because we will always have the danger of hitting this (e.g. with `variables`).

We should probably document this in our FAQ as a start (PRs welcome if you'd like to give it a shot, just let me know if you need help :) ). Or perhaps we could add a fancy `__getattr__` override to check what the user is trying to access and either warn them or try to resolve the attribute. Not sure right now how clean that solution would be.

**Comment by nejch** [comment]
Hopefully the docs are enough. From what I can tell we can't hack our `__getattr__`  to warn the user as this is usually accessed in user code and out of our control from a quick look I had. But open to ideas here :)

**Comment by sunavlis** [comment]
Hi @nejch 
Sorry for my big delay in reply to your comment. 

Your code snipped solved my issue perfectly. I didn't saw the _attributes_ property before. With this knowledge I agree with you and the API make some how sens. 
Many Thanks for your hint and the extension of the FAQ session. Hope it is also helpful for others.
