### ISSUE TITLE
Merge requests from different projects compare equal if they have the same ID

### ISSUE THREAD

**Issue by vectro** [python-gitlab/python-gitlab#2455]
It appears that `ProjectMergeRequest` uses the `iid` as the `_id_attr`; however this ID is only unique within a project. Perhaps it should use the `id` instead?

**Comment by nejch** [comment]
Thanks for the report @vectro, we're actually aware of this issue but haven't started working on a fix. Here's the original issue:

https://github.com/python-gitlab/python-gitlab/issues/935

We do need the `iid` in order to construct the URL correctly, but probably need to have a custom hash method for a few types of objects.
