### ISSUE TITLE
Support for issue health status

### ISSUE THREAD

**Issue by duncanmmacleod** [python-gitlab/python-gitlab#2553]
## Description of the problem, including code/CLI snippet

GitLab issues have a concept of [health status](https://docs.gitlab.com/ee/user/project/issues/managing_issues.html#health-status) (Ultimate feature), it would be great to be able to interact with this through the Python API.

Thanks (love python-gitlab btw).

## Expected Behavior

Setting `issue.health_status = 'needs_attention'` posts that back to gitlab via the API.

## Actual Behavior

Currently nothing happens, the unknown `health_status` option is silently ignored.

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 15.8

**Comment by nejch** [comment]
Hi @duncanmmacleod, thanks a lot for the report! First I just want to make sure you make a `issue.save()` call after this so that the PUT request is really made.

If that has no effect - are you sure the health status can be edited via the REST API?

I cannot find the attribute in the edit issue API endpoint:
https://docs.gitlab.com/ee/api/issues.html#edit-issue

If that doesn't work and you can find a way to reproduce a working PUT request to update the issue's health status, e.g. with `curl`, then we can take a look here. Otherwise, I'd say this is an upstream issue that should be reported to GitLab at https://gitlab.com/gitlab-org/gitlab. As soon as the attribute is available we can do it though.

However, as a workaround I see that you can use quick actions to change the health status, so you can also create a comment via the API with the content `/health_status needs_attention` or  `/clear_health_status`.

I don't work with Enterprise instances daily so cannot do a quick test but let us know how it goes.
