### ISSUE TITLE
Project member getting immediately removed after being added via project.invitations.create or project.members.create

### ISSUE THREAD

**Issue by ashmeetp** [python-gitlab/python-gitlab#2672]
## Description of the problem, including code/CLI snippet
When adding member to the project using python-gitlab, users are added and then immediately removed from the project. 

**Running the following code to add members to newly created project:**
`Project.members.create({"user_id": userId, "access_level": gitlab.const.AccessLevel.OWNER})`

Logs show that the members have been added:

`<class 'gitlab.v4.objects.members.ProjectMember'> => {'access_level': 50, 'created_at': '2023-10-01T05:25:41.709Z', 'created_by': [REDACTED] 'membership_state': 'active'}`

However, the members do not show up in members list for the project. Upon checking project activity, it appears that the users are being added and removed immediately. 

```
user1
left project
35 minutes ago
user2
left project
35 minutes ago
user3
left project
35 minutes ago
user1
joined project
35 minutes ago
user2
joined project
35 minutes ago
user3
joined project
35 minutes ago
gitlab_runner_ci @group_bot_
created project
ProjectName
35 minutes ago
```
![gitlab-error](https://github.com/python-gitlab/python-gitlab/assets/33167505/9f0ec141-d264-4fe8-a5d5-e41edb523933)

Members also receive email with a message "You have been granted Owner access to the xyz project.
If this was a mistake you can [leave the project]", however, when they click on the project link, they get a 404 Not Found error. 

**Also tried the alternative by inviting instead of creating members in the project:**
`Project.invitations.create({"email": email, "access_level": gitlab.const.AccessLevel.OWNER})`

This also resulted in the same behavior. The users got added and removed immediately. Upon clicking accept links they received in their emails, they were redirected to a 404 Not Found page. 

## Expected Behavior
Users are successfully added as members to the project and are not removed automatically. 

## Actual Behavior
Users are added as members to the project but are also automatically immediately removed for some reason.

## Specifications

  - python-gitlab version: 3.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): v16.1.5-ee

**Comment by nejch** [comment]
Thanks for the report @ashmeetp. I'd be surprised if this was an issue with python-gitlab and not the server, as we only make API calls to GitLab, and a create function does not make a `DELETE` request. Can you share the full snippet with us here? Does this happen when done manually?

Two theories I have is you maybe set an expiry date that immediately removes them (though not sure that's possible and it doesn't look like it from your example), or maybe a license seat issue where you cannot add additional members to your project due to EE licenses seats, but just speculating.

If you can also post a log with `gl.enable_debug()` and remove sensitive information, that might help us look at whether something is sent to the server that trips it.

Also, I'd check if you have any integrations/[webhooks](https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#group-member-events) set up in your project that might be triggering other tools to revert the change (e.g. configuration as code tools detecting drift and remediating, etc).

**Comment by nejch** [comment]
We haven't heard back so I'll close this one but please take a look at the steps above as this shouldn't really depend on the client but seems to be a server-side behavior :bow: let us know otherwise.
