### ISSUE TITLE
Webhooks return Internal Server Error

### ISSUE THREAD

**Issue by alexwidener** [python-gitlab/python-gitlab#279]
Hello, 

We're on an auto-updating :frowning: instance of Gitlab and it's up to date with 9.3, which just came out yesterday. Two days ago, I created 14 projects without a problem, today it's complaining about something to do with the webhooks. We haven't changed anything in our project creation process, it's been the same since we started using your awesome library in February. 

Here are the keys of our what the webhooks set up - 

```
  webhooks:
    url: [redacted]
    # What we want the webhook to talk about.
    build_events: False
    enable_ssl_verification: True
    issues_events: True
    merge_requests_events: True
    note_events: False
    pipeline_events: True
    push_events: False
    tag_push_events: False
    wiki_events: False
```

And here's the traceback of what's going on (I cleaned up the paths so it's easier to look at):

```
  File "the_call_from_my_library\main.py", line 196, in set_project_webhooks
    self.project.hooks.create(webhooks)
  File "\python_gitlab\0.19\Lib\site-packages\gitlab\objects.py", line 144, in create
    return self.obj_cls.create(self.gitlab, data, **args)
  File "\python_gitlab\0.19\Lib\site-packages\gitlab\objects.py", line 358, in create
    obj.save()
  File "\python_gitlab\0.19\Lib\site-packages\gitlab\objects.py", line 328, in save
    self._create(**kwargs)
  File "\python_gitlab\0.19\Lib\site-packages\gitlab\objects.py", line 313, in _create
    json = self.gitlab.create(self, **kwargs)
  File "\python_gitlab\0.19\Lib\site-packages\gitlab\__init__.py", line 513, in create
    raise_error_from_response(r, GitlabCreateError, 201)
  File "\python_gitlab\0.19\Lib\site-packages\gitlab\exceptions.py", line 180, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabCreateError: 500: 500 Internal Server Error
```

Everything outside of the webhook works fine, though. It's not a big enough problem that I need a solution, I can ignore it for now, just wanted to let you know about it. I've read around the repository and see that you're working on switching from v3 to v4 of the Gitlab API, so if it's something to do with that, it's all good.

Thanks for the hard work you put into this, it's been great using your library.

**Comment by gpocentek** [comment]
Hi @alexwidener 

Thank you for your kind words!

I've been able to reproduce the problem using the v3 API. The error in the server logs is quite explicit: `ActiveRecord::UnknownAttributeError (unknown attribute 'build_events' for ProjectHook.)`. Since it used to work I guess it's a Gitlab regression. The problem doesn't seem to exist in the v4 API though.

I don't think the GitLab team will spend a lot of time fixing v3 problems since it's been deprecated and will be completely removed in a few months. Since you continuously upgrade your GitLab installation I'd recommend starting to use the v4 API.

If you do so please have a look at issue #274, the python-gitlab API is changing a bit for v4.

**Comment by alexwidener** [comment]
Thanks for finding that, I don't have access to our Gitlab instance, so looking through logs are out of the question for me. I agree, I don't think they'll fix it, and I plan on switching over to v4 very soon - just have to find a couple of hours to put in the work :) 

Thanks again! Feel free to close this issue if you want to.
