### ISSUE TITLE
Missing content Class Variable in ProjectFile Class

### ISSUE THREAD

**Issue by GeorgeH87** [python-gitlab/python-gitlab#2821]
## Description of the problem, including code/CLI snippet
The `ProjectFile` class lacks a class variable named content, as described in the documentation. This omission results in the absence of autocomplete support for this specific field, which is inconsistent with the documented behavior.

According to the documentation, the `ProjectFile` class should contain a class variable named `content`. However, upon inspection of the codebase, it appears that this variable is missing. As a consequence, when utilizing IDEs or code editors with autocomplete features, users are unable to benefit from autocomplete support for the content field within the `ProjectFile` class.

## Expected Behavior
The `ProjectFile` class should include a class variable named `content`, as documented. This variable should be accessible and provide autocomplete support for users working with the class in various IDEs or code editors.

## Actual Behavior
1. Navigate to the `ProjectFile` class definition.
2. Attempt to access the `content` class variable or utilize autocomplete features for this field.

## Specifications
- python-gitlab-4.4.0
- Visual Studio Code 1.86.2
- python 3.11.5

**Comment by nejch** [comment]
@GeorgeH87 generally all python-gitlab objects lack auto-completion in IDEs, because the attributes are dynamically populated based on the server response, which could change depending on GitLab versions, arguments provided, and the user's privileges.

So I would definitely not rely on this in general. We only have auto-completion guaranteed for methods you can call on an object.

But `ProjectFile` is a bit special because we have custom methods that populate instance attributes a bit different from other objects. So it's a complete fluke you were able to use auto-completion for its other attributes. I'm not sure if we should add other attributes here, as it might change with GitLab versions.

**Comment by GeorgeH87** [comment]
@nejch Thanks for explaining the approach to make the project file independent of possible Gitlab API changes. I just want to point out that this explanation would break with the method `ProjectFile.decode` since it relies on `self.content`.

**Comment by nejch** [comment]
Ah nice catch @GeorgeH87, I guess we kind of depend on that then. If we're using it in the custom methods then we should add it.
