### ISSUE TITLE
Can't edit projects

### ISSUE THREAD

**Issue by novalis** [python-gitlab/python-gitlab#296]
```
import gitlab

gl = gitlab.Gitlab('https://gitlab.example.com', 'hunter2', None, None, False)
project = gl.projects.get(12345)
project.save(wiki_enabled=False)
#or
project.wiki_enabled=False
project.save()
```

I get (on 657f0119a3 against Gitlab 9.3.9):

gitlab.exceptions.GitlabUpdateError: 400: {"error":"name, description, issues_enabled, merge_requests_enabled, wiki_enabled, builds_enabled, snippets_enabled, shared_runners_enabled, container_registry_enabled, lfs_enabled, visibility, public_builds, request_access_enabled, only_allow_merge_if_pipeline_succeeds, only_allow_merge_if_all_discussions_are_resolved, path, default_branch, repository_storage, approvals_before_merge are missing, at least one parameter must be provided"}

It looks to me like the API is passing a json object in the body of the PUT request, but gitlab, for some reason, wants ?wiki_enabled=False in the URL.  Or at least that's the only way I've managed to get this working with curl.

I'm not sure if this is your bug or gitlab's bug, but I'm filing it here because it seems like your code could be changed to make this work (and then I wouldn't have to wait until my gitlab admins upgrade before I can edit projects).

**Comment by gpocentek** [comment]
Hi,

I've tested with gitlab 9.4.2 (API v3 and v4) and could not reproduce the problem, so I believe this a bug with the gitlab version you are using.

Changing the code on the python-gitlab side is not that easy, and I don't want to start dealing with the version-specific bugs. I just don't have the resources to handle that.

Since you are using the current master, what I can suggest is to use the v4 API and the `Gitlab.http_*` methods to workaround GitLab problems.

**Comment by novalis** [comment]
Yeah, indeed, it does seem to work on a more-recent gitlab version.  Thanks.
