### ISSUE TITLE
Incorrect Variable Passing in jobs.play Method

### ISSUE THREAD

**Issue by mudomudo** [python-gitlab/python-gitlab#3025]
## Description of the problem, including code/CLI snippet
There seems to be an issue with how variables are passed in the jobs.play method. When attempting to call the method with variables, the request is formatted incorrectly.

Steps to Reproduce
Call the job.play method with variables:

`job.play(variables={'KEY': 'VALUE'})`

## Expected Behavior
According to the official GitLab documentation, variables should be passed in the request body as JSON:

```
curl --request POST "https://gitlab.example.com/api/v4/projects/1/jobs/1/play" \
     --header "Content-Type: application/json" \
     --header "PRIVATE-TOKEN: <your_access_token>" \
     --data @variables.json
```
Where @variables.json contains:

```
{
  "job_variables_attributes": [
    {
      "key": "KEY",
      "value": "VALUE"
    }
  ]
}
```

## Actual Behavior
The resulting request is:

```
curl --request POST "https://gitlab.example.com/api/v4/projects/1/jobs/1/play?variables[KEY]=VALUE" \
     --header "Content-Type: application/json" \
     --header "PRIVATE-TOKEN: <your_access_token>"
```

## Additional information
If this is not a bug, it would be helpful to have more detailed documentation on this method and how to correctly pass variables. The current documentation is limited and could benefit from further elaboration. For reference, please see the documentation here: [GitLab Python API - Pipelines and Jobs](https://python-gitlab.readthedocs.io/en/stable/gl_objects/pipelines_and_jobs.html#id6).

## Specifications

  - python-gitlab version: 4.12.1
  - Gitlab server version (or gitlab.com): 16.0

**Comment by nejch** [comment]
Hi @mudomudo!

Indeed this is not a bug, but we have to follow upstream documentation for the attributes to use. It's hard sometimes for this library to replicate all the docs with GitLab so that's why we link to the API docs :)

In this case, sending arguments to the `play` endpoints is a relatively new addition after we added our docs. We can add this as to the docs it's a little less clear. If you feel like contributing a docs PR please let me know if you need any help!

This should work, let me know otherwise:

```python
data = {
    "job_variables_attributes": [
        {
            "key": "TEST_VAR_1",
            "value": "test1"
        }
    ]
}
job.play(post_data=data)
```

**Comment by mudomudo** [comment]
It worked!
Thank you :)
