### ISSUE TITLE
asyncio binding

### ISSUE THREAD

**Issue by gsemet** [python-gitlab/python-gitlab#370]
Hello. Can `python-gitlab` be ported to use asyncio (with aiohttp)? That would be of course optional but would help a lot on job-intense applications (and avoid using threads)

**Comment by gpocentek** [comment]
@Stibbons This is an interesting idea!

I guess it could be implemented but would probably require a lot of changes, while keeping the python-requests compatibility. I don't have the time to start dealing in a near future, but would be happy to review code if someone feels like implementing this feature.

Thank you for suggesting it!

**Comment by nejch** [comment]
Hi all, let's track this in https://github.com/python-gitlab/python-gitlab/issues/1025, where there's already been more discussion and a PoC implementation (though it will need a lot of rework to bring to 2022 sources). These days, httpx seems like the obvious choice due to its mostly requests-compatible API and sync+async support.

Please upvote/subscribe over there if you've been following the issue here.
