### ISSUE TITLE
all=True parameter doesn't work with project.commits.list

### ISSUE THREAD

**Issue by zhelanov** [python-gitlab/python-gitlab#373]
I've tried to get all commits from my project by passing parameter 'all=True' but it doesn't work with project.commits.list:
```
def get_all_commits(project_name):
  projects = gl.projects.list(all=True)
  for project in projects:
      if project.name == project_name:
        commits = project.commits.list(all=True)
  print(str(len(commits)))
>> 20
```
for now I've to use a workaround:
`commits = project.commits.list(page=1, per_page=10000)`

UPD: API v3

**Comment by gpocentek** [comment]
After some digging it turns out that Gitlab doesn't return proper HTTP header for commits (no `links` header). python-gitlab requires this header to loop over all available pages and return the whole list.

The v3 API is deprecated in Gitlab so I doubt it will be fixed - you can still open an issue on gitlab.com.

And the same goes for python-gitlab, I prefer not to spend time to find a workaround for deprecated code. Sorry.

**Comment by zhelanov** [comment]
So what is wrong with API v3 - I can't get **all** commits from project with python-gitlab or I just must to iterate them from page 0?
