### ISSUE TITLE
nameclash with 'pyapi-gitlab'

### ISSUE THREAD

**Issue by umlaeute** [python-gitlab/python-gitlab#385]
there's another project that provides access to the gitlab API for Python, named `pyapi-gitlab`

    https://github.com/pyapi-gitlab/pyapi-gitlab

both this project and the other one use the same import name

~~~python
import gitlab
~~~

unfortunately, the two projects have a different API...

I don't really know nor care which of the two projects has a deeper claim on the name, but i'd suggest the two projects coordinate the namespace (most likely renaming *this*).

**Comment by umlaeute** [comment]
i've also opened a ticket on the "other" project: https://github.com/pyapi-gitlab/pyapi-gitlab/issues/263

**Comment by max-wittig** [comment]
But why would you use the other project. What's missing in this one? I would vote against renaming this, as it just breaks all code based on this library.

**Comment by gpocentek** [comment]
This is indeed a problem, but:
* pyapi-gitlab seems unmaintained
* I can't think of a good reason why you would use both libs in the same project
* Unless it's a dependency problem. In that case you should probably open an issue on the project depending on pyapi-gitlab to tell them that the project doesn't seem maintained.

I know that python-gitlab is used by a bunch of other projects, so renaming it is not an option.

**Comment by umlaeute** [comment]
@gpocentek how is a project that has it's last commit 4 months ago "unmaintained"?

i'm pretty sure that there's a number of projects using `pyapi-gitlab` as well, so renaming their's is not an option either (which should answer @max-wittig's comment as well).

anyhow: i'm not necessarily thinking about having both dependencies in a single application, but rather about having both libraries installed at the same time (because they are used by different applications).
e.g. in a linux distro context, where the libraries are installed by the package manager (rather than `virtenv` or the like).

Given the Debian ecosystem (including Ubuntu,...), the `python3-gitlab` Debian package installs `pyapi-gitlab` (obviously for python3). This makes it practically impossible that *your* `python-gitlab` will be packaged for Debian (and derivatives) as well, also excluding any applications that use *your* library.

**Comment by gpocentek** [comment]
@umlaeute I see your point, and I agree with you that this is a bad situation for both libs.

That being said, I'm not willing to change the name because it's a big mess to handle. I'm already struggling to catch up with open issues and features to add, I don't want to deal with packaging/publication changes (I also didn't want to handle docker images publication for the same reason). At least not now.

If it means that python-gitlab won't make it in debian/ubuntu, well fine. Python packaging is so complicated today that I never use system packages anymore (at home or at work), and always prefer other solutions (virtualenvs, docker, or other solutions). I guess I'm not the only one doing this :)

**Comment by umlaeute** [comment]
thanks for the clarification.

@max-wittig so the reason why I do use the other project is because it is available in Debian

**Comment by the-kid89** [comment]
@gpocentek - I'm the maintainer for the other project. I just have not had time to maintain it in the past couple of months. :(
