### ISSUE TITLE
time stats are now available when listing issues

### ISSUE THREAD

**Issue by macolo** [python-gitlab/python-gitlab#392]
https://docs.gitlab.com/ee/api/issues.html#list-issues

the time_stats attribute is now available. No need to ping every single issue separately.

Also, gitlab introduced a rate limit on calls, so its not possible anymore to call every issue separately.

**Comment by gpocentek** [comment]
@macolo 

I'm not sure to understand what is the purpose of this issue. The `time_stats` attribute will be available to users if the GitLab server supports it, there's nothing to do on the python-gitlab side.

Is this not working for you?

Thanks.

**Comment by gpocentek** [comment]
Thanks for the clarification. I'll have a look at this.

**Comment by gpocentek** [comment]
Hi @macolo,

I'm not going to remove the `time_stats()` method because it is needed for older version of GitLab, it might be useful even for recent versions, and it is still supported by GitLab anyway.

I agree that having the same name for a method and a GitLab attribute is not handy, but that's also why GitLab attributes are stored in their own `attributes` dict. I've been thinking about this issue for a while but I believe that using the `attributes` dict is the way to go here.
