### ISSUE TITLE
Unable to set attributes on a user project

### ISSUE THREAD

**Issue by alexwidener** [python-gitlab/python-gitlab#437]
Hi,

Gitlab docs for what I'm trying to do:
https://docs.gitlab.com/ce/api/projects.html#create-project-for-user

I am unable to set project attributes for a UserProject. I can do this completely fine on a group project, but any of the following will not work:

```
project_attributes = {
    'wiki_enabled': False,
    'name': 'project_name',
    'description': 'some description'
}

self._active_user.projects.create(project_attributes)
```
The above will not work if I put in wiki_enabled, but works fine with name and description. Additionally, works fine if it's a group project.

```
setattr(project, 'wiki_enabled', False)
project.save()
```
This will not work.

```
data = {'wiki_enabled': False}
project.attributes.update(data)
project.save()
```
This will not work either.

What is the preferred way of setting attributes on a user project? 

Thanks!

**Comment by gpocentek** [comment]
Hi @alexwidener 

I've tested this on GitLab 10.5.2 and it worked as expected, so I guess the problem is related to the Gitlab server you're running (I've seen similar problems happen from time to time).

I see 2 possible workarounds (untested):
* do everything as an admin user but use `sudo`, something like: `gl.projects.create(project_attributes, sudo=self._active_user)`
* or create the project the way you did, but then get a `Project` instance to manipulate the attribute:
```python
user_project = self._active_user.projects.create(project_attributes)
p = gl.projects.get(user_project.id)
p.wiki_enabled = True
p.save()
```
