### ISSUE TITLE
save() of new object ignores id attr (create instead of edit)

### ISSUE THREAD

**Issue by drzraf** [python-gitlab/python-gitlab#495]
## Description of the problem, including code/CLI snippet

I attempt to modify a (remote) webhook using values from "local_webhook" as replacements in a generic enough fashion.

```python
remote_webhook =  project.hooks.get(hook_id)
new_hook_attr = {**remote_webhook.attributes, **local_webhook}
# <... intend to compare whether they are different ...>
h = ProjectHook(gl, data=new_hook_attr)
# h.id == remote_webhook.id 
try:
  h.save()
except:
  return False
return h
```

## Expected Behavior

Hook n°<hook_id> is modified

## Actual Behavior

New hook is created

## Specifications

  - python-gitlab version: 1.3.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by drzraf** [comment]
This is v4 since I was not specifying the version (confirmed printing `gl.api_version`).

**Comment by gpocentek** [comment]
Indeed `gitlab.ProjectHook` is still a internal v3 object for compatibility reasons. If you want a v4 object you need to use `gitlab.v4.objects.ProjectHook`.

The goal is to completely remove v3 references at some point since it's deprecated on the server side, and stop exposing the objects in the `gitlab` namespace.
