### ISSUE TITLE
Question about retrieving subgroups from a group

### ISSUE THREAD

**Issue by matthewaerose** [python-gitlab/python-gitlab#508]
## Description of the problem, including code/CLI snippet
I am trying to retrieve a list of sub groups from a group.

`group = gl.groups.get(id)`
`subgroups = group.subgroups.list()`

## Expected Behavior
Expected behavior is that the call returns with a list of subgroups

## Actual Behavior
Instead of a list, I get the error
`gitlab.exceptions.GitlabListError: 404: b'{"error":"404 Not Found"}'`

## Specifications

  - python-gitlab version: 1.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Server Version: ('10.1.3-ee', '7748fef')

## Note
This is similar to Issue #463, but I have more information!

**Comment by gpocentek** [comment]
python-gitlab tries to implement all the features available in the GitLab v4 API, without any specific version target. This means that if the feature you are trying to use (subgroups in your case) is not available, you'll get a 404 error because the endpoint doesn't exist on the server side (subgroups API has been added in 10.3).

This actually follows the GitLab vision for their API (basically no minor/micro version): https://docs.gitlab.com/ee/api/#compatibility-guidelines

**Comment by matthewaerose** [comment]
Thank you for the answer! I appreciate it.
