### ISSUE TITLE
pyinstaller / cxfreeze issue in __inti__.py

### ISSUE THREAD

**Issue by jd-mtb** [python-gitlab/python-gitlab#509]
## Description of the problem, including code/CLI snippet
If you use this module in a project and try to compile it into an exe using pyinstaller or cxfreeze there is a dependency issue. In __init__.py on line 104 there is a dynamic module load which is not detected. As a workaround I was able to add the below line on line 36 so that it was explicitly loaded and able to be found by pyinstaller. 

"""
import gitlab.v4.objects
"""

Since v3 is depricated this change or something more appropriate could probably be put in the code to prevent further trouble for folks building using those tools.

**Comment by gpocentek** [comment]
Hi @jd-mtb 

The goal of the import on line 104 is to load the proper API version at runtime, so loading the v4 objects explicitly is something I would like to avoid (I just got rid of the historical v3 import in master). The problem will appear again when the v5 API is ready if we go this way, so it's not a proper solution.

I've had a quick look at pyinstaller, and wrote a very basic test program. Adding the import in the test program instead of python-gitlab seems to do the trick.

Another solution is to patch pyinstaller to detect dynamic import.

**Comment by jd-mtb** [comment]
Hi @gpocentek 

I don't mind the explicit import in the main program, that is a much better temporary solution I glossed over. I just tested and this works well for me.

I suspect that with pyinstaller and cxfreeze being around as long as they have this has been tried before on their end. If there's no better solution and dynamic imports are needed (assuming it isn't easily removable, or that users want multiple api versions in the same module going forward) then there might not be anything to do other than note how it impacts compiling into exe's.

**Comment by gpocentek** [comment]
The following seems to work: `pyinstaller --hidden-import=gitlab.v4.objects` and it looks like cx_freeze has the same kind of option.

**Comment by willstott101** [comment]
I'm a bit confused by this... I have a few questions:
* Is v3 currently supported anyway?
* Would importing both really be that bad if there are multiple different api modules?
* Why not use a runtime import with a normal import statement, which PyInstaller will find and include automatically?

i.e.
```python
if config.api_version == "4":
    from gitlab.v4 import cli as cli_module
else:
    # error out cause the version is invalid.
```

**Comment by nejch** [comment]
Hi @willstott101, I think the original idea was to support several versions without fiddling with imports, although it's true v5 doesn't seem to be anywhere close and the versions move slow long enough that normal imports would probably be more readable.

Otherwise, this can be solved pretty easily without any change to the code by using PyInstaller hooks (https://pyinstaller.readthedocs.io/en/stable/hooks.html#understanding-pyinstaller-hooks), which could be packaged with `python-gitlab`, or even provide a PyInstaller executable if there's demand?

It's been a while since I last worked with PyInstaller but it should be pretty simple.

https://pyinstaller.readthedocs.io/en/stable/hooks.html#provide-hooks-with-package
