### ISSUE TITLE
Why is this project hosted on GitHub?

### ISSUE THREAD

**Issue by norpol** [python-gitlab/python-gitlab#539]
First of all, thank you for this API "wrapper" - I'm a happy python-gitlab user and I'm very thankful for it's existence.
I hope it's alright that I'm creating an issue for that, but I'm really curious; Why is this project hosted on GitHub and not GitLab? :-)

**Comment by max-wittig** [comment]
Github is the most popular social coding platform right now. I could be mirrored to GitLab and CI could run there maybe.

**Comment by gpocentek** [comment]
Hi @norpol 

When the python-gitlab development started more than 5 years ago gitlab.com wasn't really an option, and the project stayed on github.com. I'm used to it and it work just fine.

It would make sense to move the project to gitlab.com today, but this means that the CI has to be moved from travis to gitlab CI. It's the main blocker for me, and it will probably be time consuming to do this migration. Since I have limited time to work on this project I'm not focusing on that right now. If someone provides a `.gitlab-ci.yml` that provides the same testing than what we have on Travis then we can plan a migration.

**Comment by max-wittig** [comment]
Instead of moving, I would suggest a mirror to GitLab. Keep the project and GitHub and GitLab. GitHub should still be the main platform to develop this, as most people are here (also gitlab.com is still slow/unreachable from time to time...)

**Comment by gpocentek** [comment]
@max-wittig I don't really see the point of only mirroring on GitLab. I'm afraid it would only add confusion for people trying to report issues or create MR there instead of using github.

I'm closing this issue since I think the original question is answered :)
