### ISSUE TITLE
gl object for the Project-merge-approvals setting after project creation?

### ISSUE THREAD

**Issue by AkhilaDamera** [python-gitlab/python-gitlab#576]
## python-GitLab CLI command for the Merge Request Settings?

I am trying to provide a group name for the merge request approvals under the merge request settings of a project and did not find exact command for this.

I have tried with the " gitlab -c 'Config.cfg' project create --name test --path xx --description testing --merge-requests-enabled true
But I need to add a group as the merge request approvals. Could you please let me know if there is command already available for this or not.

![gitlab-merge-approvals](https://user-images.githubusercontent.com/6663492/44818788-3b2df580-abb8-11e8-874c-b5e0c7ffc3ff.PNG)
  - python-gitlab version: stable 
  - API version you are using (v3/v4): v4

Appreciate your help.

Thanks,
Akhila

**Comment by gpocentek** [comment]
Hi @AkhilaDamera 

Adding the groups is not possible using the CLI for now, but it exist in the python API. I'll do my best to add this in the next release.

**Comment by nejch** [comment]
This issue is very old and the API has changed since then, but the usage with the new API is documented in the auto-generated CLI docs:

https://python-gitlab.readthedocs.io/en/stable/cli-objects.html#gitlab-project-approval-rule-create

`gitlab project-approval-rule create --project-id PROJECT_ID --name NAME --approvals-required APPROVALS_REQUIRED [--user-ids USER_IDS] [--group-ids GROUP_IDS]`

For approval rules on a specific MR, see https://python-gitlab.readthedocs.io/en/stable/cli-objects.html#gitlab-project-merge-request-approval-rule-create.
