### ISSUE TITLE
Make lazy object fetch the data when an attribute is requested

### ISSUE THREAD

**Issue by gpocentek** [python-gitlab/python-gitlab#730]
## Description of the problem, including code/CLI snippet

Lazy object never fetch the data. So they are not lazy, they just refuse to work :)

They could fetch the data when access to an attribute is performed.

## Expected Behavior

```
project = gl.projects.get(project_id, lazy=True)
print(project.name)  # fetches the object internally then prints the project name 
```

## Actual Behavior

```
project = gl.projects.get(project_id, lazy=True)
print(project.name)  # Raises AttributeError
```

## Specifications

  - python-gitlab version: All
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): Any, not related

**Comment by max-wittig** [comment]
But how should they fetch the data then? With `simple=True` or should they just fetch the whole object?

I think raising AttributeErrorshould be expected behavior, when a `lazy` call is performed.
Related to https://github.com/python-gitlab/python-gitlab/issues/711

**Comment by vikramuk** [comment]
Hi,
  with V1.8 we note that .list() i.e. lazy call and .list(all=true) are not similar 

*** from Release Note 1.8 ***
The following example only works with the new parameter:
activities = gl.user_activities.list(query_parameters={'from': '2019-01-01'},all=True)
 
Listed Valid query_parameter listed as  **ref_name**, **since** and **until** filters to limit the results:
commits = project.commits.list(**ref_name**='my_branch').

**Question :** does this mean we need to specify the query_parameter for 'ref_name' to refer to the Branches() as referred to by repo_branches attribute?.

Specific case: api/v4/projects/1163/repository/branches lists these branches.

>   "SVN",
>   "master",
>   "newStructure",
>   "singleton_engine",
>   "portingValveCore",

What would i need to do to get the list of all commits?.
commits = project.commits.list(ref_name='master').?.



***
python-gitlab version: 11.3.x
API version you are using (v3/v4): v4
Gitlab server version (or gitlab.com): 1.8

**Comment by gpocentek** [comment]
@max-wittig my idea was to fetch the whole object when an attribute is accessed.

**Comment by gpocentek** [comment]
@vikramuk please open a new issue if you still need an answer.

**Comment by max-wittig** [comment]
@gpocentek Sounds reasonable, but could also be confusing. If it crashes it reminds people to not access the attribute of the object as they cause API calls otherwise. I would say we shouldn't change the behaviour of this lazy attribute.

**Comment by gpocentek** [comment]
@max-wittig OK, bad idea then. Thanks for your input!
