### ISSUE TITLE
CLI: how to list commit in all branches in a project?

### ISSUE THREAD

**Issue by hapablanha** [python-gitlab/python-gitlab#751]
## Description of the problem, including code/CLI snippet
I ran gitlab project-commit list and got something like below, which is lack of details.
id: 5ae8bfc5806c13d47e932c39ae164b58b864cd0b
title: 修复getallfilename不兼容win10的问题

id: 160436738016963da9b043cfdc24622abe94642c
title: 优化代码

id: 021fb3a743c38c13094707d5f9560da262601d64
title: 添加项目文件。

id: 40c84dff754a9bbb3b8c56db9fc89cbc2d513d9a
title: 添加 .gitignore 和 .gitattributes。

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by hapablanha** [comment]
I used CLI command below.
GitLab -o json project-commit -project 1 --all

I only got the commits in master branch.

**Comment by zoidbergwill** [comment]
`all` sounds like it should do the right thing: https://docs.gitlab.com/ee/api/commits.html#list-repository-commits

**Comment by zoidbergwill** [comment]
Oh, I think it's because the `all` is being swallowed by the library as "fetch all pages for this resource" and not being sent as a query param to the API.

Which you can see with the following:

```
 GitLab -d -o json project-commit list --project-id 1 --all  
```

**Comment by monsdar** [comment]
I stumbled across the same issue, but using the Python API. The docs mention the conflict, but did not help very much. I solved it by doing the following: `project.commits.list(all=True, query_parameters={'all': True, 'since': '2016-01-01T00:00:00Z'})`

**Comment by nejch** [comment]
@monsdar would the proposed solution in https://github.com/python-gitlab/python-gitlab/pull/1458/files work better for you?

**Comment by monsdar** [comment]
Sounds like this will cause a lot of confusion where users expect `all=True` to return all pages while in only some cases it returns something else.

I did not check the code in depth: Is it possible to always use `all_pages=True` instead of `all=True`? I'd then change the docs etc to have `all_pages=True` as the new default and only for backwards-compatibility keep support for `all=True` to return all pages when the API does not conflict. This way there is no breaking change, but users won't get confused as easily.
