### ISSUE TITLE
How to create a job with init README？

### ISSUE THREAD

**Issue by Tiger-zzZ** [python-gitlab/python-gitlab#765]
## Description of the problem, including code/CLI snippet
I want to use `gitlab project create ...` to create a job and Initialize repository with a README,
but there is no options.
gitlab api https://docs.gitlab.com/ee/api/projects.html#create-project in create job has option `initialize_with_readme`.
in the last i use this command create README .`gitlab project-file create --project-id $(shell cat REPO_INFO | grep 'id' | sed 's/^id: //g') --file-path README.md --branch master --content '# makefile-init' --commit-message init-with-makefile`
if there has better choice?

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by nejch** [comment]
Hi @Tiger-zzZ, this is quite late but there are two options:

1. If you just need an placeholder README so that you have a cloneable repo with a master branch, then the following will be enough after #1067 is merged:

```
gitlab project create --path "your-repo" --initialize-with-readme true
```

2. If you need specific content, as shown in your post above with `--content 'your content'`, then I think your approach makes sense. The GitLab API (or UI) does not provide a way to already provide the content of the readme when creating projects with READMEs initialized.
