### ISSUE TITLE
Assignee for issue not set on creation

### ISSUE THREAD

**Issue by maxwhosevillage** [python-gitlab/python-gitlab#810]
## Description of the problem, including code/CLI snippet
I created an issue like this:
```python
issue = p.issues.create({
    'title': title,
    'description': description,
    'assignee_ids': [2,],
     })
```

## Expected Behavior
Issue created ans assignee is set.

## Actual Behavior
Issue created but the assignee is **not** set.

## Specifications

  - python-gitlab version: 1.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.0 CE

**Comment by max-wittig** [comment]
Did you try it with curl, yet? Often Gitlab itself has a small minor issues

**Comment by maxwhosevillage** [comment]
Just tried for half an hour to find a way to work it out with curl.
Also with curl the issue is created but the assignee is not set.
Really sad! ;-( 
Does anyone has an idea what to do?

**Comment by max-wittig** [comment]
You can for example set it after issue creation. 
```python
issue = p.issues.create...
issue.assignee_ids = [2, ]
issue.save()
```

This is untested.

**Comment by vlntnwbr** [comment]
I just ran into a similar problem and tried the workaround provided by @max-wittig, which worked perfectly.
I'm using Python 3.7, python-gitlab v1.8  and the server is running Gitlab v12.1 EE.

I created the issue like this:

``
project = gitlab.Gitlab().projects.get(6)
issue = project.issues.create(
        {
            "title": "Automation Test",
            "description": "This is not a drill",
            "due_date": "2019-10-24",
            "milestone_id": 2,
            "assignee_ids": [user.id for user in project.members.list()]
        }
    )
``

**Comment by max-wittig** [comment]
Seems to be an upstream issue then

**Comment by deckar01** [comment]
This does not appear to be an upstream issue. The type for this parameter is documented as `integer array`. The docs say arrays should be encoded with PHP-style array keys.

https://docs.gitlab.com/ee/api/README.html#array

The type of labels is string and explicitly documented as a comma separated string. The API is expecting `assignee_ids[]=1&assignee_ids[]=2` instead of `assignee_ids=1,2`.

https://gitlab.com/gitlab-org/gitlab/-/issues/27472

Possible fixes:

- Hard code a mapping of which parameters need which encoding
- Accept `set` and use the array key encoding for it
