### ISSUE TITLE
migrate to asyncio

### ISSUE THREAD

**Issue by L0ric0** [python-gitlab/python-gitlab#945]
## Description of the problem, including code/CLI snippet

all the requests done in this module are syncronous. to use it more efficiently all requests should be converted to https://aiohttp.readthedocs.io/en/stable/ to make them concurrent

## Expected Behavior

posibility for concurrent requests

## Actual Behavior

only syncronus requests

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

**Comment by max-wittig** [comment]
Or [httpx](https://github.com/encode/httpx)

I would be open to review any MR regarding this topic.

**Comment by mitar** [comment]
The issue with async behavior is how to handle rate limiting. Just throwing bunch of requests into async queue can be tricky. You need some throttling.

**Comment by L0ric0** [comment]
how should the migration be implemented? if we just change all methods to async current users will have to change there code but if we create our own event loop other async programs can't take full advantage of the async features.

should we create a event loop in the gitlab object which could be handed to it from the __init__?

**Comment by nejch** [comment]
Let's track progress on this in #1025 if that's ok with you, as it has things fleshed out a bit more and httpx is the most requests-compatible alternative, maybe upvote there or otherwise let us know here if this should be reopened.

For rate limits, most likely something like https://github.com/florimondmanca/aiometer/ would help (also by httpx devs).
